services:
  # Основной контейнер с приложением
  hh-app:
    build: .
    container_name: hh-app
    # Оставляем контейнер запущенным, чтобы Ofelia могла заходить в него по расписанию
    command: tail -f /dev/null
    env_file: .env
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    labels:
      ofelia.enabled: "true"
      # Этот пиво-сосичный ублюдок по-ходу это не добавил
      ofelia.job-exec.hh-apply.run-on-startup: "true"
      ofelia.job-exec.hh-apply.schedule: ${OFELIA_SCHEDULE:-@every 4h}
      ofelia.job-exec.hh-apply.command: "python main.py -f -mr 500 -v -u $SEARCH_URL"

  # Планировщик Ofelia
  scheduler:
    image: mcuadros/ofelia:latest
    container_name: hh-scheduler
    depends_on:
      - hh-app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./logs:/logs
    restart: unless-stopped
    # labels:
    #   ofelia.save-folder: "/logs"
